name: log_file_server
description: A server app using the shelf package to manage TankController log files.
version: 25.1.1
repository: https://github.com/Open-Acidification/TankController

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  args: ^2.3.0
  csv: ^6.0.0
  intl: ^0.20.2
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^6.0.0
  test: ^1.21.0
