name: reverse_proxy
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.2.0
  shelf_proxy: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
