# This is the name of the workflow, visible on GitHub UI
name: Arduino CI

# Run on a Push or a Pull Request
on: [push, pull_request]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest
    steps:
      # Clone the repo using the `checkout` action
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Run Arduino-CI Tests
        run: |
          g++ -v
          cd server
          gem --version
          gem update --system --quiet --silent
          gem --version
          scripts/install_libraries.sh
          scripts/testAndBuild.sh

      - name: Ensure no Git changes
        run: |
          cd server
          git status -s -uno
          cat server/size.txt
          (exit `git status -s -uno | wc -l`)
