name: Flutter Web
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # To push a branch 
      pull-requests: write  # To create a PR from that branch

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install and Build ğŸ”§
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: |
          echo "build for web"
          cd extras/webClient
          flutter --version
          flutter pub get
          flutter build web --release --base-href="/TankControllerManager/"
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: extras/webClient/build/web # The folder the action should deploy.
