    name: Flutter tests
    on: [pull_request, push, workflow_dispatch]
    jobs:
      Flutter_Tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - uses: subosito/flutter-action@v2
        - run: |
            cd extras/web_client
            flutter test --concurrency=1
